### ISSUE TITLE
API Integration with Reporting API

### ISSUE THREAD

**Issue by Brandr0id** [privacycg/storage-access#33]
On our Chromium implementation doc @mikewest pondered if we should integrate API failures with the [Reporting API](https://www.w3.org/TR/reporting-1/).

Potentially we could send an [InterventionReport](https://www.w3.org/TR/reporting-1/#intervention-report) when requestStorageAccess() is rejected.

What does everything think about this integration point?

**Comment by hober** [comment]
> On our Chromium implementation doc

Sounds like an interesting read. Is it public?

> @mikewest pondered if we should integrate API failures with the [Reporting API](https://www.w3.org/TR/reporting-1/).
> 
> Potentially we could send an [InterventionReport](https://www.w3.org/TR/reporting-1/#intervention-report) when requestStorageAccess() is rejected.
> 
> What does everything think about this integration point?

I'm not familiar with the Reporting API, but offhand this doesn't sound like a bad idea.

**Comment by hober** [comment]
I think this is a really cool idea, though as with many ideas the devil may be in the details. Clearly it would be valuable for site owners to get aggregated error information like "70% of calls to requestStorageAccess() fail because  of `reason`", but there would be a lot of infrastructure needed to aggregate such reports. I'd like us to revisit this in a future version.
